---
- hosts: lojas
  remote_user: root

  tasks:

  - name: "EXPORT"
    command: "{{ item }}"
    with_items:
    - export http_proxy="http://tinet:c3rt3l,9191.@proxy.certel.com.br:8080"
    - export https_proxy="https://tinet:c3rt3l,9191.@proxy.certel.com.br:8080"

  - name: "apt-get update"
    apt: update_cache=yes
