---
- hosts: host
  remote_user: root

  tasks:

  - name: "EXPORT"
    command: "{{ item }}"
    with_items:
    - export http_proxy="http://user:passwd.@proxy.com.br:port"
    - export https_proxy="https://user:passwd.@proxy.com.br:port"

  - name: "apt-get update"
    apt: update_cache=yes
