---
- hosts: host
  become: yes
  tasks:
  - name: Export http
    shell: export http_proxy="http://user:passwd.@proxy.com.br:port"
  - name: Export https
    shell: export https_proxy="https://user:passwd.@proxy.com.br:port"
  - name: update
    shell: apt update
